# inventory.ini
# Define your Ubuntu hosts here

[ubuntu_servers]
# Add your servers below. Examples:
 server1 ansible_host=10.200.9.125
 server2 ansible_host=10.200.9.201
 server3  ansible_host=10.200.9.112 ansible_user=ubuntu

[ubuntu_servers:vars]
ansible_user=ubuntu                        # Default SSH user for Ubuntu instances
ansible_ssh_private_key_file=/mnt/c/Users/UITS/.ssh/id_rsa.pub # Key used for INITIAL connection (bootstrap key)
ansible_python_interpreter=/usr/bin/python3
